# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whk < Formula
  desc "CLI tool for webhooks.cc - Inspect, forward, and replay webhooks"
  homepage "https://webhooks.cc"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.6.0/whk_darwin_amd64.tar.gz"
      sha256 "f742d3bb28e9d0efd35d5d555d086b02e67e9902ea0106ff8944e99b66adba8b"

      define_method(:install) do
        bin.install "whk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.6.0/whk_darwin_arm64.tar.gz"
      sha256 "f79c3c0985bf67a828fbc41b150a9887487d83bb8bb2bff1f25447837047c961"

      define_method(:install) do
        bin.install "whk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.6.0/whk_linux_amd64.tar.gz"
      sha256 "f9a7d4c22d4766277efd9a6273b3338b44a4c891fc88959bc2dc8d2b4d22e6a7"
      define_method(:install) do
        bin.install "whk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.6.0/whk_linux_arm64.tar.gz"
      sha256 "4efa1fd2f063fdb2ac6b05de7904377a79b7e53c5cf3cd765064de75f5665e55"
      define_method(:install) do
        bin.install "whk"
      end
    end
  end

  test do
    system "#{bin}/whk", "--version"
  end
end
