# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whk < Formula
  desc "CLI tool for webhooks.cc - Inspect, forward, and replay webhooks"
  homepage "https://webhooks.cc"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.1/whk_darwin_amd64.tar.gz"
      sha256 "411c4d9f7b9558b73629da731619a9c0516a2b9c164a4d23cccfb05dba97e86f"

      def install
        bin.install "whk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.1/whk_darwin_arm64.tar.gz"
      sha256 "0d69807fe0a9032ddee3155ec2d8a55909438833b5155197be092e85243895c3"

      def install
        bin.install "whk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.1/whk_linux_amd64.tar.gz"
      sha256 "a81740c2a541eaacffbf34258307d8c3ddf23d34c164d5d11b81a94eabc58475"
      def install
        bin.install "whk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.1/whk_linux_arm64.tar.gz"
      sha256 "9136c4ab114fd5a4c085c018c5378749a50caaab8f8ff66db823d086ce006489"
      def install
        bin.install "whk"
      end
    end
  end

  test do
    system "#{bin}/whk", "--version"
  end
end
