# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whk < Formula
  desc "CLI tool for webhooks.cc - Inspect, forward, and replay webhooks"
  homepage "https://webhooks.cc"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.2/whk_darwin_amd64.tar.gz"
      sha256 "55d8a4167768fc983ead61beaf305f61497e11d649212d9e9f6f9d813dd16aa9"

      define_method(:install) do
        bin.install "whk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.2/whk_darwin_arm64.tar.gz"
      sha256 "f5f555e1a080e548a759a2068d001983945870def6f1fa960a64dce46fa0a288"

      define_method(:install) do
        bin.install "whk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.2/whk_linux_amd64.tar.gz"
      sha256 "3ccf2d53ebd6f1ff8557397c83e8be5fff70f20e93595fd2a394882de41679ac"
      define_method(:install) do
        bin.install "whk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kroqdotdev/webhooks-cc/releases/download/v0.5.2/whk_linux_arm64.tar.gz"
      sha256 "2c9d381093d95b116fa34a6fcea7801621357381a4c805455cf26cd111a6ecdb"
      define_method(:install) do
        bin.install "whk"
      end
    end
  end

  test do
    system "#{bin}/whk", "--version"
  end
end
